events {}

http {
    upstream webcam_backend {
        server webcam:8000;
    }

    server {
        listen 80;

        location /stream {
            proxy_pass http://webcam_backend/stream;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            chunked_transfer_encoding on;
        }

        location /health {
            proxy_pass http://webcam_backend/health;
        }
    }
}